/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as DoctorPanelIndexRouteImport } from './routes/doctor-panel.index'
import { Route as DoctorAuthIndexRouteImport } from './routes/doctor-auth.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as ChatDoctorIdRouteImport } from './routes/chat.$doctorId'
import { Route as BookingDoctorIdRouteImport } from './routes/booking.$doctorId'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPanelIndexRoute = DoctorPanelIndexRouteImport.update({
  id: '/doctor-panel/',
  path: '/doctor-panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAuthIndexRoute = DoctorAuthIndexRouteImport.update({
  id: '/doctor-auth/',
  path: '/doctor-auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatDoctorIdRoute = ChatDoctorIdRouteImport.update({
  id: '/chat/$doctorId',
  path: '/chat/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDoctorIdRoute = BookingDoctorIdRouteImport.update({
  id: '/booking/$doctorId',
  path: '/booking/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/favorites': typeof FavoritesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/chat/$doctorId': typeof ChatDoctorIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/doctor-auth/': typeof DoctorAuthIndexRoute
  '/doctor-panel/': typeof DoctorPanelIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/favorites': typeof FavoritesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/chat/$doctorId': typeof ChatDoctorIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/auth': typeof AuthIndexRoute
  '/doctor-auth': typeof DoctorAuthIndexRoute
  '/doctor-panel': typeof DoctorPanelIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/favorites': typeof FavoritesRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/chat/$doctorId': typeof ChatDoctorIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/doctor-auth/': typeof DoctorAuthIndexRoute
  '/doctor-panel/': typeof DoctorPanelIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/favorites'
    | '/online'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/booking/$doctorId'
    | '/chat/$doctorId'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/articles/'
    | '/auth/'
    | '/doctor-auth/'
    | '/doctor-panel/'
    | '/specialties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/favorites'
    | '/online'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/booking/$doctorId'
    | '/chat/$doctorId'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/articles'
    | '/auth'
    | '/doctor-auth'
    | '/doctor-panel'
    | '/specialties'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/favorites'
    | '/online'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/booking/$doctorId'
    | '/chat/$doctorId'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/articles/'
    | '/auth/'
    | '/doctor-auth/'
    | '/doctor-panel/'
    | '/specialties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  FavoritesRoute: typeof FavoritesRoute
  OnlineRoute: typeof OnlineRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  BookingDoctorIdRoute: typeof BookingDoctorIdRoute
  ChatDoctorIdRoute: typeof ChatDoctorIdRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DoctorAuthIndexRoute: typeof DoctorAuthIndexRoute
  DoctorPanelIndexRoute: typeof DoctorPanelIndexRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-panel/': {
      id: '/doctor-panel/'
      path: '/doctor-panel'
      fullPath: '/doctor-panel/'
      preLoaderRoute: typeof DoctorPanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-auth/': {
      id: '/doctor-auth/'
      path: '/doctor-auth'
      fullPath: '/doctor-auth/'
      preLoaderRoute: typeof DoctorAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$doctorId': {
      id: '/chat/$doctorId'
      path: '/chat/$doctorId'
      fullPath: '/chat/$doctorId'
      preLoaderRoute: typeof ChatDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$doctorId': {
      id: '/booking/$doctorId'
      path: '/booking/$doctorId'
      fullPath: '/booking/$doctorId'
      preLoaderRoute: typeof BookingDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  FavoritesRoute: FavoritesRoute,
  OnlineRoute: OnlineRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  BookingDoctorIdRoute: BookingDoctorIdRoute,
  ChatDoctorIdRoute: ChatDoctorIdRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DoctorAuthIndexRoute: DoctorAuthIndexRoute,
  DoctorPanelIndexRoute: DoctorPanelIndexRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
